error: Add some history (and populate date).
Longer term, I think it would be interesting to add tabs which
flip thorugh the different histories instead of a big list.